name: Telegram Hourly Poster

on:
  schedule:
    # Runs at minute 0 of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message to Telegram Channel
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            --data-urlencode "chat_id=@tgminiappsupdates" \
            --data-urlencode "text=Buying Old Tinder Accounts 🔥

          2010 – 2024 (All Months) = 22 USDT
          2025 first 5 months 17
          All age accepted
          2025 also 1-5 months

          We need old tinder account 
          2025 7-12 girl account . tekegram bot is Kreegyrbot"
